dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "nightly"
before_install:
  - pip install poetry
  - pip install tox-travis
install:
  - poetry install
  - poetry build
script:
  - black --line-length 79 --check src
  - make -C docs html
  - tox
